'use strict';
/** Enumerations from the Backend Schema document (single source of truth). */

const ROLES = Object.freeze({ PATIENT: 'PATIENT', DOCTOR: 'DOCTOR', ADMIN: 'ADMIN' });

const VERIFICATION_STATUS = Object.freeze({ PENDING: 'PENDING', APPROVED: 'APPROVED', REJECTED: 'REJECTED' });

const RELATION_STATUS = Object.freeze({
  PENDING: 'PENDING', APPROVED: 'APPROVED', REJECTED: 'REJECTED', REVOKED: 'REVOKED',
});

const PERMISSION_STATUS = Object.freeze({ GRANTED: 'GRANTED', REVOKED: 'REVOKED', EXPIRED: 'EXPIRED' });

const RECORD_TYPES = Object.freeze([
  'LAB_REPORT', 'IMAGING', 'PRESCRIPTION', 'DISCHARGE_SUMMARY', 'CONSULTATION_NOTE', 'VACCINATION', 'OTHER',
]);

/** Audit actions: the schema's examples first, then the additional events the app flow requires. */
const AUDIT_ACTIONS = Object.freeze([
  'LOGIN', 'RECORD_UPLOAD', 'ACCESS_REQUEST', 'ACCESS_GRANTED', 'ACCESS_REJECTED', 'ACCESS_REVOKED',
  'RECORD_VIEW', 'HASH_VERIFICATION', 'TAMPER_DETECTED',
  'REGISTER', 'LOGIN_FAILED', 'LOGOUT',
  'DOCTOR_APPROVED', 'DOCTOR_REJECTED',
  'CONSULTATION_ADDED', 'PROFILE_UPDATED', 'WALLET_LINKED',
  'ACCESS_DENIED', 'ACCESS_EXPIRED', 'RECORD_HASH_ANCHORED',
  'EMERGENCY_ACCESS',
]);

module.exports = { ROLES, VERIFICATION_STATUS, RELATION_STATUS, PERMISSION_STATUS, RECORD_TYPES, AUDIT_ACTIONS };
